

services:
  indexmon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: indexmon
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./data:/app/data
    env_file:
      - .env